### ISSUE TITLE
environmental variables have to be manually set

### ISSUE THREAD

**Issue by CharmedSatyr** [CharmedSatyr/charmed_cash#2]
Have not figured out how to keep the environmental variables from being stringified and loaded into the code by dotenv (dotenv-webpack doesn't like me when I use when bundling the server...).

The package currently runs on Heroku because I manually removed environmental variables and replaced them with 'process.env.PORT', etc.

**Comment by xhad** [comment]
Could it be a Heroku deployment issue? Perhaps the .env is not making it to heroku?

**Comment by CharmedSatyr** [comment]
Hey, thanks for your comment! I fixed this by *not* defining the environmental variables in webpack config using environmentPlugin/DefinePlugin and instead allowing their values to be defined dynamically in the production environment with values loaded into or assigned by Heroku. (I was confused about what those plugins were for.) Belatedly marking this issue as closed. :)
